### ISSUE TITLE
Character limit on production names: 31 or 63?

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/agl-specification#2]
https://github.com/adobe-type-tools/agl-specification says:

> [...] Both of these require that a glyph name be no longer than 31 characters in length [...]

The OpenType Feature File Specification says:

> A glyph name may be up to 63 characters in length [...].

I suppose the former is just about production names for the `post` table and the latter just about design names, but would like an official clarification.

**Comment by anthrotype** [comment]
I may be selective, but the way I read the Feature File spec is that it's referring to the production names' limitations, not the design names'

> For production glyph names [...] These limitations are as follows. A glyph name may be up to 63 characters in length [...]

**Comment by moyogo** [comment]
The `post` table definition in the OpenType specification points to the AGL specification, so that is what implementations will most likely adhere to, if they bother at all.

Given the following https://github.com/adobe-type-tools/afdko/pull/99#issue-55745059
> readroberts wrote on Sep 25, 2015: "About the 31 character limit in
PostScript glyph names: although the spec clearly states the limit of
31 characters, I increased the limit in the AFDKO tools to 63 a year
or to ago for practical reasons. Use of the rules to name complex
ligatures leads to longer glyph names, and I had reasonable use cases
that would exceed this limit. A number of the limits stated in the
spec are not in fact enforced any the rasterizes I have available for
testing. I changed this limit in the AFDKO tools in order to test if
we could in practice get away with longer glyph names. Although there
are few such cases, I have not heard of any reports of difficulties. I
agree that the spec should be changed."
>
> fontforge/fontforge#2500 (comment)

maybe it’s fine to update the AGL spec as well to the 63 character limit for glyph names.

**Comment by kenlunde** [comment]
Thank you, @madig, for reporting this, and to others for the dialog. We discussed this among team members, and the result were adjustments in Section 6. Version 2.8, which I just published, now reflects 63 characters as the length-limit for glyph names.
